---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    region: "us-east-2"
    instance_type: "t2.micro"
    ami_id: "ami-024e6efaf93d85776"  
    key_name: "HaiKeyPair"
    security_group: "sg.full"
    subnet_id: "subnet-0c234106b405b8541"
  tasks:
    - name: Create EC2 Instance
      ec2:
        aws_access_key: "AKIAVSDMGM3UHPE5S7HL"
        aws_secret_key: "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"
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ subnet_id }}"
        wait: yes
        count: "{{ instances | length }}"
        assign_public_ip: yes
      register: ec2_instance
    - name: Display EC2 Instance Information
      debug:
        var: ec2_instance.instances
